[project]
name = "aws-canary-telemetry-grafana"
version = "0.1.0"
description = "Canary service to test availability of Grafana"
authors = [{ name = "Team Telemetry", email = "telemetry@digital.hmrc.gov.uk" }]
license = "Apache 2.0"
maintainers = [{ name = "Team Telemetry", email = "telemetry@digital.hmrc.gov.uk" }]
readme = "README.md"
requires-python = ">=3.12,<3.13"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "aws-lambda-powertools"
]

[dependency-groups]
dev = [
    "bandit",
    "black",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "pytest-ruff",
    "toml",
    "version-incrementor>=1.5.0,<2",
    "wheel",
    "boto3",
    "selenium>=4.32.0,<4.33",
]

[tool.coverage.html]
directory = "output/htmlcov"

[tool.coverage.run]
source = ["./src"]

[tool.coverage.report]
fail_under = 70

[tool.pytest.ini_options]
log_cli = true
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_level = "INFO"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_level = "INFO"
python_files = ["tests.py", "test_*.py", "*_tests.py", "*_test.py"]
addopts = [
    "--ruff",
    "--cov=./src",
    "--no-cov-on-fail",
    "-p no:warnings"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W"]        # pycodestyle-equivalent checks

[tool.uv]
package = false
default-groups = "all"

[[tool.uv.index]]
name = "artifactory"
url = "https://artefacts.tax.service.gov.uk/artifactory/api/pypi/pips/simple/"
default = true

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
