#!/usr/bin/env bash
#MISE description="Run commands specific to the CodeBuild PR requirements"
#MISE env={PIP_INDEX_URL="https://artefacts.tax.service.gov.uk/artifactory/api/pypi/pips/simple", SKIP="no-commit-to-branch,doctoc"}
#MISE raw=true

uv run pre-commit run --all-files --verbose
