#!/usr/bin/env bash
#MISE description="Prepare dependencies and run unit tests in a Docker environment"
#MISE depends=["setup", "bandit", "black"]
#MISE raw=true

PYTHON_VERSION=$(python --version | awk '{print $2}')

uv export --format requirements.txt \
          --index-url "${PIP_INDEX_URL}" \
          --no-annotate \
          --no-hashes \
          --no-header \
          --output-file "requirements-tests.txt" \
          --quiet

docker build \
           --platform 'linux/amd64' \
           --build-arg DOCKER_REPO="${DOCKER_REPO}" \
           --build-arg PYTHON_VERSION="${PYTHON_VERSION}" \
           --build-arg PIP_INDEX_URL="${PIP_INDEX_URL}" \
           --build-arg REQUIREMENTS_FILE="requirements-tests.txt" \
           -t aws-canary-telemetry-grafana-test \
           .

docker run --rm \
           --tty \
           --platform 'linux/amd64' \
           --volume "${MISE_CONFIG_ROOT}:/data" \
           aws-canary-telemetry-grafana-test /data/bin/test.sh
